// <auto-generated />
using System;
using AdminApi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AdminApi.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    partial class AdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("axon")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdminApi.Domain.Entities.AgentProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("agent_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("PurposeId")
                        .HasColumnType("integer")
                        .HasColumnName("purpose_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("WebhookAuthTokenEncrypted")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("webhook_auth_token_encrypted");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("webhook_url");

                    b.HasKey("ProfileId")
                        .HasName("pk_agent_profiles");

                    b.HasIndex("PurposeId")
                        .HasDatabaseName("ix_agent_profiles_purpose_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_agent_profiles_tenant_id");

                    b.ToTable("agent_profiles", "axon");
                });

            modelBuilder.Entity("AdminApi.Domain.Entities.AgentPurpose", b =>
                {
                    b.Property<int>("PurposeId")
                        .HasColumnType("integer")
                        .HasColumnName("purpose_id");

                    b.Property<string>("BaseSystemPrompt")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("base_system_prompt");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("PurposeId")
                        .HasName("pk_agent_purposes");

                    b.ToTable("agent_purposes", "axon");

                    b.HasData(
                        new
                        {
                            PurposeId = 1,
                            BaseSystemPrompt = "You are an order processing agent for a retail store. Help customers check product availability and place orders. Always confirm order details before placing.",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "E-Commerce Order Taking"
                        },
                        new
                        {
                            PurposeId = 2,
                            BaseSystemPrompt = "You are a receptionist scheduling medical appointments. Help patients find available slots and book appointments. Always confirm the patient's name, date, and service type.",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Clinic Appointment Booking"
                        },
                        new
                        {
                            PurposeId = 3,
                            BaseSystemPrompt = "You are a helpful customer service agent. Answer questions based on the provided knowledge base. If you don't know the answer, say so honestly.",
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "General FAQ"
                        });
                });

            modelBuilder.Entity("AdminApi.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("event_type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("ProcessedAtUtc")
                        .HasDatabaseName("ix_outbox_messages_processed_at_utc");

                    b.ToTable("outbox_messages", "axon");
                });

            modelBuilder.Entity("AdminApi.Domain.Entities.TenantKnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(384)")
                        .HasColumnName("embedding");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("TextChunk")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text_chunk");

                    b.HasKey("Id")
                        .HasName("pk_tenant_knowledge_bases");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_tenant_knowledge_bases_embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_tenant_knowledge_bases_profile_id");

                    b.ToTable("tenant_knowledge_bases", "axon");
                });

            modelBuilder.Entity("AdminApi.Domain.Entities.AgentProfile", b =>
                {
                    b.HasOne("AdminApi.Domain.Entities.AgentPurpose", "Purpose")
                        .WithMany("Profiles")
                        .HasForeignKey("PurposeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_agent_profiles_agent_purposes_purpose_id");

                    b.Navigation("Purpose");
                });

            modelBuilder.Entity("AdminApi.Domain.Entities.AgentPurpose", b =>
                {
                    b.Navigation("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
